title: BINH LE VAN
description: >-
  data enthusiast <br /> Quote<a href="https://html5up.net">HTML5 UP</a>
logo: images/logo.svg

address: Hanoi - Vietnam
phone: (+84) 868 426 648
email: binhlevan1999@gmail.com

socials:
  Twitter: "#"
  Facebook: "#"
  Instagram: "#"
  GitHub: "#"
  Dribbble: "#"
